name: ezy_appbuilder
description: "A Flutter application that allows users to build apps using JSON configuration."
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: 3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  json_ui_builder:
    # path: ../json_ui_builder
    git:
      url: https://github.com/mahadydev/json_ui_builder

  shared_preferences: 2.5.3
  freezed_annotation: 3.1.0
  json_annotation: 4.9.0
  device_frame: 1.4.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
  build_runner: 2.5.4
  freezed: 3.1.0
  json_serializable: 6.9.5
  riverpod_lint: ^2.6.5
  custom_lint: ^0.7.5
  riverpod_generator: ^2.6.5

flutter:
  uses-material-design: true
